# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20171220_1548'),
        ('bot_stat', '0002_auto_20171206_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Месяц')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
                ('function', models.CharField(db_index=True, max_length=50)),
                ('count', models.IntegerField(default=0, verbose_name='Количество вызовов')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_functions', to='bot.Subscribers')),
            ],
        ),
    ]
