# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_stat', '0003_usedfunctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedfunctions',
            name='month',
        ),
        migrations.RemoveField(
            model_name='usedfunctions',
            name='year',
        ),
    ]
