# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.SmallIntegerField(db_index=True, max_length=6, unique=True, verbose_name='Номер карты')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания абонемента')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активация абонемента')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название абонемента')),
            ],
            options={
                'verbose_name': 'карта клиента',
                'verbose_name_plural': 'карты клиентов',
            },
        ),
    ]
