# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_1c', '0002_auto_20180121_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_number',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Номер карты'),
        ),
    ]
