# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_1c', '0003_auto_20180121_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='exp_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата окончания абонемента'),
        ),
    ]
