# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание группы')),
                ('timetable', models.TextField(blank=True, null=True, verbose_name='Расписание занятий')),
                ('is_default', models.BooleanField(default=False, verbose_name='Группа по-умолчанию')),
            ],
            options={
                'verbose_name': 'группа рассылки',
                'verbose_name_plural': 'группы рассылки',
            },
        ),
        migrations.CreateModel(
            name='PhotoMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Максимальный размер - 5 Мб', null=True, upload_to='messages_img', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Максимум 200 символов', max_length=200, verbose_name='Текст описания')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(default=False, editable=False, verbose_name='Отправлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_messages', to='bot.Groups', verbose_name='Группа для рассылки')),
            ],
            options={
                'verbose_name': 'сообщение с картинкой',
                'verbose_name_plural': 'сообщения с картинкой',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор пользователя')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('subscribing_status', models.CharField(blank=True, max_length=5, null=True, verbose_name='В процессе подписки')),
            ],
            options={
                'verbose_name': 'подписчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
        migrations.CreateModel(
            name='SubscribersInGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribition_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='bot.Groups')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='bot.Subscribers')),
            ],
            options={
                'verbose_name': 'подписчики в группах',
                'verbose_name_plural': 'подписчики в группах',
            },
        ),
        migrations.CreateModel(
            name='TextMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(default=False, editable=False, verbose_name='Отправлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='bot.Groups', verbose_name='Группа для рассылки')),
            ],
            options={
                'verbose_name': 'текстовое сообщение',
                'verbose_name_plural': 'текстовые сообщения',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscribersingroups',
            unique_together=set([('subscriber', 'group')]),
        ),
    ]
