# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст приветствия для новых подписчиков')),
            ],
            options={
                'verbose_name': 'текст приветствия для новых подписчиков',
                'verbose_name_plural': 'текст приветствия для новых подписчиков',
            },
        ),
    ]
