# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20171205_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcometext',
            name='text',
            field=models.TextField(verbose_name='Текст приветствия для новых подписчиков'),
        ),
    ]
