# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20171210_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание группы'),
        ),
    ]
