# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20171218_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='exp_date_staff',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения полномочий админа'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscribing_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='В процессе подписки'),
        ),
    ]
