# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20171220_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessages',
            name='text',
            field=models.TextField(default='', help_text='Максимум 200 символов(поле не обязательно для заполнения)', max_length=200, verbose_name='Текст описания'),
        ),
    ]
