# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20180504_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessages',
            name='text',
            field=models.TextField(blank=True, help_text='Максимум 200 символов(поле не обязательно для заполнения)', max_length=200, null=True, verbose_name='Текст описания'),
        ),
    ]
